micronaut:
  application:
    name: itemRecommendation
endpoints:
  health:
    enabled: true
    sensitive: false
#tag::jaeger[]
tracing:
  jaeger:
    enabled: true
    sampler:
      probability: 1.0 # <1>



#end::jaeger[]


